env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  project: ./tsconfig.json
  sourceType: module
plugins:
  - react
  - react-hooks
  - '@typescript-eslint'
  - jsx-a11y
  - unused-imports
  - import
rules:
  sort-imports: off
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      alphabetize:
        order: asc
  'react/prop-types': 'off'
  unused-imports/no-unused-imports-ts: warn
  no-magic-numbers: off
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: off
  react/react-in-jsx-scope: off
  react/self-closing-comp: [error, { component: true, html: true }]
  '@typescript-eslint/no-unused-vars': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/array-type': [error, { default: array }]
  '@typescript-eslint/naming-convention':
    [
      error,
      {
        selector: interface,
        format: [PascalCase],
      },
      {
        selector: typeAlias,
        format: [PascalCase],
      },
    ]
